model:
  name: MNIST_MLP  # This model is defined in model_defs.py. Add your own model definitions there.
  # The model is from "Training Certifiably Robust Neural Networks with Efficient Local Lipschitz Bounds (Huang et al., NeurIPS 2021)"
  # wget https://github.com/yjhuangcd/local-lipschitz/raw/main/pretrained/relu/cifar_4C3F_best.pth
  path: ./sdp_crown_experiment/models/mnist_mlp.pth
general:
  save_output: mnist_mlp.txt
data:
  dataset: MNIST_SDP  # Dataset name. This is just the standard CIFAR-10 test set defined in the "load_verification_dataset()" function in utils.py
  start: 0
  end: 1
specification:
  norm: 2  # Linf norm (can also be 2 or 1).
  epsilon: 1.0 # epsilon=36./255.
attack:  # Currently attack is only implemented for Linf norm. Skip for L2 norm.
  pgd_order: skip
solver:
  alpha-crown:
    iteration: 200   # Number of iterations for alpha-CROWN optimization. Alpha-CROWN is used to compute all intermediate layer bounds before branch and bound starts.
    lr_alpha: 0.5    # Learning rate for alpha in alpha-CROWN. The default (0.1) is typically ok.
    max_time: 10
  batch_size: 1024  # Number of subdomains to compute in parallel in bound solver. Decrease if you run out of memory.
bab:
  timeout: 120  # Timeout threshold for branch and bound. Increase for verifying more points.
